
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `cNORM`=list(
        `type`="software", 
        `author`="Lenhard, W.; Lenhard, A.; Gary, S.", 
        `year`=2018, 
        `title`="cNORM: Continuous Norming", 
        `publisher`="[R package]. Retrieved from https://CRAN.R-project.org/package=cNORM", 
        `url`="https://CRAN.R-project.org/package=cNORM"))
