
# This file is automatically generated, you probably don't want to edit this

continuousOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "continuousOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            raw = NULL,
            group = NULL,
            scale = "T",
            k = "Quartic",
            terms = "4",
            descend = FALSE,
            normAge = NULL,
            model = TRUE, ...) {

            super$initialize(
                package='Norming',
                name='continuous',
                requiresData=TRUE,
                ...)

            private$..raw <- jmvcore::OptionVariable$new(
                "raw",
                raw,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..scale <- jmvcore::OptionList$new(
                "scale",
                scale,
                options=list(
                    "T",
                    "IQ",
                    "z",
                    "Wechsler",
                    "PISA"),
                default="T")
            private$..k <- jmvcore::OptionList$new(
                "k",
                k,
                options=list(
                    "Quadratic",
                    "Cubic",
                    "Quartic"),
                default="Quartic")
            private$..terms <- jmvcore::OptionList$new(
                "terms",
                terms,
                options=list(
                    "Automatic",
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6",
                    "7",
                    "8",
                    "9",
                    "10",
                    "11",
                    "12",
                    "13",
                    "14",
                    "15",
                    "16"),
                default="4")
            private$..descend <- jmvcore::OptionBool$new(
                "descend",
                descend,
                default=FALSE)
            private$..normAge <- jmvcore::OptionString$new(
                "normAge",
                normAge)
            private$..model <- jmvcore::OptionBool$new(
                "model",
                model,
                default=TRUE)

            self$.addOption(private$..raw)
            self$.addOption(private$..group)
            self$.addOption(private$..scale)
            self$.addOption(private$..k)
            self$.addOption(private$..terms)
            self$.addOption(private$..descend)
            self$.addOption(private$..normAge)
            self$.addOption(private$..model)
        }),
    active = list(
        raw = function() private$..raw$value,
        group = function() private$..group$value,
        scale = function() private$..scale$value,
        k = function() private$..k$value,
        terms = function() private$..terms$value,
        descend = function() private$..descend$value,
        normAge = function() private$..normAge$value,
        model = function() private$..model$value),
    private = list(
        ..raw = NA,
        ..group = NA,
        ..scale = NA,
        ..k = NA,
        ..terms = NA,
        ..descend = NA,
        ..normAge = NA,
        ..model = NA)
)

continuousResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        plot = function() private$.items[["plot"]],
        norms = function() private$.items[["norms"]],
        model = function() private$.items[["model"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Continuous Norming")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                width=600,
                height=400,
                visible=TRUE,
                renderFun=".plot"))
            self$add(jmvcore::Table$new(
                options=options,
                name="norms",
                title="Norm score table",
                rows=1,
                visible=FALSE,
                columns=list(
                    list(
                        `name`="Raw", 
                        `type`="number"),
                    list(
                        `name`="Norm", 
                        `type`="number"),
                    list(
                        `name`="Percentile", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="model",
                title="Model summary",
                visible=TRUE))}))

continuousBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "continuousBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'Norming',
                name = 'continuous',
                version = c(1,0,0),
                options = options,
                results = continuousResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Continuous Norming
#'
#' 
#' @param data the data as a data frame
#' @param raw a string specifying the raw score variable in \code{data}
#' @param group a string specifying the grouping variable in \code{data}
#' @param scale \code{'T'}, \code{'IQ'}, 'z', 'Wechsler subtest scale (m = 10,
#'   sd = 3)', or 'PISA (m = 500, sd = 100)'`
#' @param k .
#' @param terms .
#' @param descend .
#' @param normAge a number specifying the age for the norm score table
#' @param model .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$norms} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$model} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$norms$asDF}
#'
#' \code{as.data.frame(results$norms)}
#'
#' @export
continuous <- function(
    data,
    raw,
    group,
    scale = "T",
    k = "Quartic",
    terms = "4",
    descend = FALSE,
    normAge,
    model = TRUE) {

    if ( ! requireNamespace('jmvcore'))
        stop('continuous requires jmvcore to be installed (restart may be required)')

    if ( ! missing(raw)) raw <- jmvcore::resolveQuo(jmvcore::enquo(raw))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(raw), raw, NULL),
            `if`( ! missing(group), group, NULL))


    options <- continuousOptions$new(
        raw = raw,
        group = group,
        scale = scale,
        k = k,
        terms = terms,
        descend = descend,
        normAge = normAge,
        model = model)

    analysis <- continuousClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
