
# This file is automatically generated, you probably don't want to edit this

conventionalOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "conventionalOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            raw = NULL,
            scale = "T",
            k = TRUE,
            terms = "4",
            descend = FALSE,
            plotting = "Norm Score",
            model = TRUE, ...) {

            super$initialize(
                package='Norming',
                name='conventional',
                requiresData=TRUE,
                ...)

            private$..raw <- jmvcore::OptionVariable$new(
                "raw",
                raw)
            private$..scale <- jmvcore::OptionList$new(
                "scale",
                scale,
                options=list(
                    "T",
                    "IQ",
                    "z",
                    "Wechsler",
                    "PISA"),
                default="T")
            private$..k <- jmvcore::OptionBool$new(
                "k",
                k,
                default=TRUE)
            private$..terms <- jmvcore::OptionList$new(
                "terms",
                terms,
                options=list(
                    "1",
                    "2",
                    "3",
                    "4",
                    "5"),
                default="4")
            private$..descend <- jmvcore::OptionBool$new(
                "descend",
                descend,
                default=FALSE)
            private$..plotting <- jmvcore::OptionList$new(
                "plotting",
                plotting,
                options=list(
                    "Norm Score",
                    "Percentile"),
                default="Norm Score")
            private$..model <- jmvcore::OptionBool$new(
                "model",
                model,
                default=TRUE)

            self$.addOption(private$..raw)
            self$.addOption(private$..scale)
            self$.addOption(private$..k)
            self$.addOption(private$..terms)
            self$.addOption(private$..descend)
            self$.addOption(private$..plotting)
            self$.addOption(private$..model)
        }),
    active = list(
        raw = function() private$..raw$value,
        scale = function() private$..scale$value,
        k = function() private$..k$value,
        terms = function() private$..terms$value,
        descend = function() private$..descend$value,
        plotting = function() private$..plotting$value,
        model = function() private$..model$value),
    private = list(
        ..raw = NA,
        ..scale = NA,
        ..k = NA,
        ..terms = NA,
        ..descend = NA,
        ..plotting = NA,
        ..model = NA)
)

conventionalResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        plot = function() private$.items[["plot"]],
        norms = function() private$.items[["norms"]],
        model = function() private$.items[["model"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Norm Score Modeling of Single Groups")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                refs="assessment",
                visible=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                refs="cNORM",
                width=600,
                height=400,
                visible=TRUE,
                renderFun=".plot"))
            self$add(jmvcore::Table$new(
                options=options,
                name="norms",
                title="Norm score table",
                refs="epm",
                rows=1,
                columns=list(
                    list(
                        `name`="Raw", 
                        `type`="integer"),
                    list(
                        `name`="Norm", 
                        `type`="number"),
                    list(
                        `name`="Percentile", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="model",
                title="Model summary",
                visible=TRUE))}))

conventionalBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "conventionalBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'Norming',
                name = 'conventional',
                version = c(1,0,0),
                options = options,
                results = conventionalResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Single Group
#'
#' 
#' @param data the data as a data frame
#' @param raw a string specifying the raw score variable in \code{data}
#' @param scale \code{'T'}, \code{'IQ'}, 'z', 'Wechsler subtest scale (m = 10,
#'   sd = 3)', or 'PISA (m = 500, sd = 100)'`
#' @param k .
#' @param terms .
#' @param descend .
#' @param plotting .
#' @param model .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$norms} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$model} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$norms$asDF}
#'
#' \code{as.data.frame(results$norms)}
#'
#' @export
conventional <- function(
    data,
    raw,
    scale = "T",
    k = TRUE,
    terms = "4",
    descend = FALSE,
    plotting = "Norm Score",
    model = TRUE) {

    if ( ! requireNamespace('jmvcore'))
        stop('conventional requires jmvcore to be installed (restart may be required)')

    if ( ! missing(raw)) raw <- jmvcore::resolveQuo(jmvcore::enquo(raw))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(raw), raw, NULL))


    options <- conventionalOptions$new(
        raw = raw,
        scale = scale,
        k = k,
        terms = terms,
        descend = descend,
        plotting = plotting,
        model = model)

    analysis <- conventionalClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
