
# This file is automatically generated, you probably don't want to edit this

conventionalOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "conventionalOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            raw = NULL,
            weights = NULL,
            scale = "T",
            k = TRUE,
            terms = "4",
            descend = FALSE,
            plotting = "Norm Score",
            range = 3,
            model = TRUE,
            minRaw = 0,
            maxRaw = 0,
            stepping = 1, ...) {

            super$initialize(
                package="cNORMj",
                name="conventional",
                requiresData=TRUE,
                ...)

            private$..raw <- jmvcore::OptionVariable$new(
                "raw",
                raw,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..weights <- jmvcore::OptionVariable$new(
                "weights",
                weights,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..scale <- jmvcore::OptionList$new(
                "scale",
                scale,
                options=list(
                    "T",
                    "IQ",
                    "z",
                    "Wechsler",
                    "PISA"),
                default="T")
            private$..k <- jmvcore::OptionBool$new(
                "k",
                k,
                default=TRUE)
            private$..terms <- jmvcore::OptionList$new(
                "terms",
                terms,
                options=list(
                    "1",
                    "2",
                    "3",
                    "4",
                    "5"),
                default="4")
            private$..descend <- jmvcore::OptionBool$new(
                "descend",
                descend,
                default=FALSE)
            private$..plotting <- jmvcore::OptionList$new(
                "plotting",
                plotting,
                options=list(
                    "Norm Score",
                    "Percentile"),
                default="Norm Score")
            private$..range <- jmvcore::OptionNumber$new(
                "range",
                range,
                default=3)
            private$..model <- jmvcore::OptionBool$new(
                "model",
                model,
                default=TRUE)
            private$..minRaw <- jmvcore::OptionNumber$new(
                "minRaw",
                minRaw,
                default=0)
            private$..maxRaw <- jmvcore::OptionNumber$new(
                "maxRaw",
                maxRaw,
                default=0)
            private$..stepping <- jmvcore::OptionNumber$new(
                "stepping",
                stepping,
                default=1)
            private$..manifestNorms <- jmvcore::OptionOutput$new(
                "manifestNorms")
            private$..predictedNorms <- jmvcore::OptionOutput$new(
                "predictedNorms")
            private$..saveManifest <- jmvcore::OptionOutput$new(
                "saveManifest")
            private$..saveManifestPerc <- jmvcore::OptionOutput$new(
                "saveManifestPerc")
            private$..savePredicted <- jmvcore::OptionOutput$new(
                "savePredicted")
            private$..savePredictedPerc <- jmvcore::OptionOutput$new(
                "savePredictedPerc")

            self$.addOption(private$..raw)
            self$.addOption(private$..weights)
            self$.addOption(private$..scale)
            self$.addOption(private$..k)
            self$.addOption(private$..terms)
            self$.addOption(private$..descend)
            self$.addOption(private$..plotting)
            self$.addOption(private$..range)
            self$.addOption(private$..model)
            self$.addOption(private$..minRaw)
            self$.addOption(private$..maxRaw)
            self$.addOption(private$..stepping)
            self$.addOption(private$..manifestNorms)
            self$.addOption(private$..predictedNorms)
            self$.addOption(private$..saveManifest)
            self$.addOption(private$..saveManifestPerc)
            self$.addOption(private$..savePredicted)
            self$.addOption(private$..savePredictedPerc)
        }),
    active = list(
        raw = function() private$..raw$value,
        weights = function() private$..weights$value,
        scale = function() private$..scale$value,
        k = function() private$..k$value,
        terms = function() private$..terms$value,
        descend = function() private$..descend$value,
        plotting = function() private$..plotting$value,
        range = function() private$..range$value,
        model = function() private$..model$value,
        minRaw = function() private$..minRaw$value,
        maxRaw = function() private$..maxRaw$value,
        stepping = function() private$..stepping$value,
        manifestNorms = function() private$..manifestNorms$value,
        predictedNorms = function() private$..predictedNorms$value,
        saveManifest = function() private$..saveManifest$value,
        saveManifestPerc = function() private$..saveManifestPerc$value,
        savePredicted = function() private$..savePredicted$value,
        savePredictedPerc = function() private$..savePredictedPerc$value),
    private = list(
        ..raw = NA,
        ..weights = NA,
        ..scale = NA,
        ..k = NA,
        ..terms = NA,
        ..descend = NA,
        ..plotting = NA,
        ..range = NA,
        ..model = NA,
        ..minRaw = NA,
        ..maxRaw = NA,
        ..stepping = NA,
        ..manifestNorms = NA,
        ..predictedNorms = NA,
        ..saveManifest = NA,
        ..saveManifestPerc = NA,
        ..savePredicted = NA,
        ..savePredictedPerc = NA)
)

conventionalResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "conventionalResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        plot = function() private$.items[["plot"]],
        norms = function() private$.items[["norms"]],
        modelTab = function() private$.items[["modelTab"]],
        manifestNorms = function() private$.items[["manifestNorms"]],
        predictedNorms = function() private$.items[["predictedNorms"]],
        saveManifest = function() private$.items[["saveManifest"]],
        saveManifestPerc = function() private$.items[["saveManifestPerc"]],
        savePredicted = function() private$.items[["savePredicted"]],
        savePredictedPerc = function() private$.items[["savePredictedPerc"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Single Group")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                refs="assessment",
                visible=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                refs="cNORM",
                width=600,
                height=400,
                visible=TRUE,
                renderFun=".plot"))
            self$add(jmvcore::Table$new(
                options=options,
                name="norms",
                title="Norm score table",
                refs="epm",
                visible=TRUE,
                rows=1,
                columns=list(
                    list(
                        `name`="Raw", 
                        `type`="number"),
                    list(
                        `name`="Norm", 
                        `type`="number"),
                    list(
                        `name`="Percentile", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="modelTab",
                title="Model Summary",
                visible=TRUE,
                rows=1,
                refs="plos",
                columns=list(
                    list(
                        `name`="Variable", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Weight", 
                        `type`="number"),
                    list(
                        `name`="Terms", 
                        `type`="integer"),
                    list(
                        `name`="RMSE", 
                        `type`="number"),
                    list(
                        `name`="R2adj", 
                        `type`="number"),
                    list(
                        `name`="BIC", 
                        `type`="number"))))
            self$add(jmvcore::Output$new(
                options=options,
                name="manifestNorms",
                title="Manifest Norm Scores",
                varTitle="ManifestNorms",
                varDescription="Frequency-based norm scores",
                measureType="continuous"))
            self$add(jmvcore::Output$new(
                options=options,
                name="predictedNorms",
                title="Predicted Norm Scores",
                varTitle="predictedNorms",
                varDescription="Regression-based norm scores",
                measureType="continuous"))
            self$add(jmvcore::Output$new(
                options=options,
                name="saveManifest",
                title="Manifest Norm Scores",
                varTitle="ManifestNorm",
                varDescription="Manifest norm score",
                measureType="continuous",
                clearWith=list(
                    "raw",
                    "weights",
                    "scale",
                    "descend")))
            self$add(jmvcore::Output$new(
                options=options,
                name="saveManifestPerc",
                title="Manifest Percentile Scores",
                varTitle="ManifestPercentile",
                varDescription="Manifest percentile score",
                measureType="continuous",
                clearWith=list(
                    "raw",
                    "weights",
                    "scale",
                    "descend")))
            self$add(jmvcore::Output$new(
                options=options,
                name="savePredicted",
                title="Fitted Norm Scores",
                varTitle="FittedNorm",
                varDescription="Fitted norm score",
                measureType="continuous",
                clearWith=list(
                    "raw",
                    "weights",
                    "scale",
                    "k",
                    "descend",
                    "terms")))
            self$add(jmvcore::Output$new(
                options=options,
                name="savePredictedPerc",
                title="Fitted Percentile Scores",
                varTitle="FittedPercentile",
                varDescription="Fitted percentile score",
                measureType="continuous",
                clearWith=list(
                    "raw",
                    "weights",
                    "scale",
                    "k",
                    "descend",
                    "terms")))}))

conventionalBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "conventionalBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "cNORMj",
                name = "conventional",
                version = c(2,0,0),
                options = options,
                results = conventionalResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Single Group
#'
#' 
#' @param data the data as a data frame
#' @param raw a string specifying the raw score variable in \code{data}
#' @param weights on optional weighting variable, specifying the weights of
#'   the single cases
#' @param scale \code{'T'}, \code{'IQ'}, 'z', 'Wechsler subtest scale (m = 10,
#'   sd = 3)', or 'PISA (m = 500, sd = 100)'`
#' @param k .
#' @param terms .
#' @param descend .
#' @param plotting .
#' @param range .
#' @param model .
#' @param minRaw .
#' @param maxRaw .
#' @param stepping .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$norms} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$modelTab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$manifestNorms} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$predictedNorms} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$saveManifest} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$saveManifestPerc} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$savePredicted} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$savePredictedPerc} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$norms$asDF}
#'
#' \code{as.data.frame(results$norms)}
#'
#' @export
conventional <- function(
    data,
    raw,
    weights,
    scale = "T",
    k = TRUE,
    terms = "4",
    descend = FALSE,
    plotting = "Norm Score",
    range = 3,
    model = TRUE,
    minRaw = 0,
    maxRaw = 0,
    stepping = 1) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("conventional requires jmvcore to be installed (restart may be required)")

    if ( ! missing(raw)) raw <- jmvcore::resolveQuo(jmvcore::enquo(raw))
    if ( ! missing(weights)) weights <- jmvcore::resolveQuo(jmvcore::enquo(weights))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(raw), raw, NULL),
            `if`( ! missing(weights), weights, NULL))


    options <- conventionalOptions$new(
        raw = raw,
        weights = weights,
        scale = scale,
        k = k,
        terms = terms,
        descend = descend,
        plotting = plotting,
        range = range,
        model = model,
        minRaw = minRaw,
        maxRaw = maxRaw,
        stepping = stepping)

    analysis <- conventionalClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

